### PR TITLE
feat: create a task without prompts using flags

### PR DESCRIPTION
**Pull request by Alasdair-Munday**
## Related Issue

https://github.com/DarthBenro008/rchore/issues/16

## Description

`tasks new` can now be run with:
 - A positional argument for title
 - A flag `--note` or `-n` for adding a note
 - A flag `--completed` or -c for setting the task to complete when adding it

If the title is provided then the prompts for the rest of the information don't run.

I know it doesnt quite match the issue description but I wanted to try and follow the existing names for things. (title instead of name etc.)

### Type
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation

### Additional information for maintainers

I've never written rust before so apologies if i've done something silly / un-idiomatic. I'm happy to change anything you want changed.

- Added optional fields for flags to the Add struct
- Forked logic in `TaskManager::add_task` to not prompt for values if title is provided or prompt for any title and flags that weren't provided if title isn't passed as an arg

#### Help printout:
```
❯ ./target/debug/rchore tasks add -h
rchore-tasks-add 0.1.0
Create a new task in the task-list

USAGE:
    rchore tasks add [FLAGS] [OPTIONS] [title]

FLAGS:
    -c, --completed    Set the tasks status to completed
    -h, --help         Prints help information
    -V, --version      Prints version information

OPTIONS:
    -n, --notes <notes>    A short description of the task

ARGS:
    <title>    The title of the task
```

#### Create a task with just title
```
❯ ./target/debug/rchore tasks add 'new task with no flags'
Yay! :)
Task new task with no flags has been created!
```
image

#### Create a task with flags set but no title
```
❯ ./target/debug/rchore tasks add -c -n 'new task with note'
✔ Title of the task · title of task with other flags set
Yay! :)
Task title of task with other flags set has been created!
```
image

#### Create a task with title and all flags
```
❯ ./target/debug/rchore tasks add 'task with flags' -c -n 'new task with all flags set'
Yay! :)
Task task with flags has been created!
```
image

### CODE REVIEW

**Comment by DarthBenro008** [comment]
Hey @Alasdair-Munday ! Thanks for opening this PR! apologies for the delay in reviewing the PR. I can see that `clippy` has some suggestions regarding the code. Could you please amend the same? You can view a detailed message in the results of the CI

**Comment by Alasdair-Munday** [comment]
Thanks! that should have fixed the clippy issues now

**Comment by DarthBenro008** [comment]
Thanks for creating this PR @Alasdair-Munday ! 🎉 Great work!

**Comment by Whyglobaleyes** [comment]
hello all,

this looks really good and timesaving

is it a thing? has the feature above been integrated to the main rchore tool (I installed using cargo)?

**Pull request merged**
